package com.example.core_api.api_models

enum class Currencies(val description: String) {
  AUD("Australian Dollar — Австралийский доллар (Австралия)"),
  BGN("Bulgarian Lev — Болгарский лев (Болгария)"),
  BRL("Brazilian Real — Бразильский реал (Бразилия)"),
  CAD("Canadian Dollar — Канадский доллар (Канада)"),
  CHF("Swiss Franc — Швейцарский франк (Швейцария)"),
  CNY("Chinese Yuan — Китайский юань (Китай)"),
  CZK("Czech Koruna — Чешская крона (Чехия)"),
  DKK("Danish Krone — Датская крона (Дания)"),
  EUR("Euro — Евро (Еврозона)"),
  GBP("British Pound Sterling — Фунт стерлингов (Великобритания)"),
  HKD("Hong Kong Dollar — Гонконгский доллар (Гонконг)"),
  HRK("Croatian Kuna — Хорватская куна (Хорватия)"),
  HUF("Hungarian Forint — Венгерский форинт (Венгрия)"),
  IDR("Indonesian Rupiah — Индонезийская рупия (Индонезия)"),
  ILS("Israeli Shekel — Израильский шекель (Израиль)"),
  INR("Indian Rupee — Индийская рупия (Индия)"),
  ISK("Icelandic Króna — Исландская крона (Исландия)"),
  JPY("Japanese Yen — Японская иена (Япония)"),
  KRW("South Korean Won — Южнокорейская вона (Южная Корея)"),
  MXN("Mexican Peso — Мексиканское песо (Мексика)"),
  MYR("Malaysian Ringgit — Малайзийский ринггит (Малайзия)"),
  NOK("Norwegian Krone — Норвежская крона (Норвегия)"),
  NZD("New Zealand Dollar — Новозеландский доллар (Новая Зеландия)"),
  PHP("Philippine Peso — Филиппинское песо (Филиппины)"),
  PLN("Polish Zloty — Польский злотый (Польша)"),
  RON("Romanian Leu — Румынский лей (Румыния)"),
  RUB("Russian Ruble — Российский рубль (Россия)"),
  SEK("Swedish Krona — Шведская крона (Швеция)"),
  SGD("Singapore Dollar — Сингапурский доллар (Сингапур)"),
  THB("Thai Baht — Тайский бат (Таиланд)"),
  TRY("Turkish Lira — Турецкая лира (Турция)"),
  USD("United States Dollar — Доллар США (Соединенные Штаты Америки)"),
  ZAR("South African Rand — Южноафриканский ранд (Южная Африка")
}